# Generated by Django 4.2.3 on 2023-07-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/banner_imgs')),
                ('discount_deal', models.CharField(max_length=100)),
                ('quotes', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
