# Generated by Django 4.2.3 on 2023-07-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_slug_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='shop_Product',
        ),
    ]
